### ISSUE TITLE
Project will not open in Visual Studio 2010 Ultimate

### ISSUE THREAD

**Issue by DWRoelands** [qerub/ReplaceEmbeddedAssemblyResource#1]
I have NuGet installed, when when I download the solution and open it in Visual Studio 2010 the project will not load.

![projectload](https://cloud.githubusercontent.com/assets/829031/4080199/b9b786ee-2edc-11e4-8e8c-da6a70c12c6d.png)

Also, I see that the solution uses the Mono.Cecil library, but that library is not in the ZIP file that came from GitHub.

**Comment by qerub** [comment]
> […] when I download the solution and open it in Visual Studio 2010 the project will not load.

The project was created with Xamarin Studio and it seems it managed to create something VS2010 can't open. I don't have access to VS2010 at the moment, so your best bet is probably to regenerate the project file yourself and send me a pull request.

> Also, I see that the solution uses the Mono.Cecil library, but that library is not in the ZIP file that came from GitHub.

You should be able to ask NuGet to pull down Mono.Cecil for you once the above issue is resolved. (The dependency is declared in packages.config.)

**Comment by DWRoelands** [comment]
The NuGet package wouldn't retrieve.

Struggled with it for about an hour, then ported the project to VB in a
brand new Visual Studio Solution. Thanks for sharing the code!

**Comment by dee-see** [comment]
It didn't open in VS2013 either. The reason is that somehow the .nuget directory was not downloaded by the GitHub windows client and therefore the `<Import Project="$(SolutionDir)\.nuget\nuget.targets" />` directive fails while loading the .csproj. I simply commented that out as it isn't needed anymore for package restore with newer versions of NuGet...

edit: Oh, it's because the .nuget folder is not in the repository! haha

**Comment by qerub** [comment]
Resolved with #4. Closing.
